name: _offline
timestamp: 1530484406
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _offline
  timestamp: 1505845335
positions:
  cr-logo: Logo
  find-us: 'Find Us'
  quik-links: 'Quick Links'
  send-a-message: 'Send A message'
sections:
  header: Header
  navigation: Navigation
  sidebar: Sidebar
  mainbar: Mainbar
  abovefooter: Abovefooter
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  content:
    system-content-1246: 'Page Content'
  custom:
    custom-2410: 'Header Contact'
    custom-8180: 'Footer Menu'
  social:
    social-6386: Social
  logo:
    logo-6694: Logo
  menu:
    menu-2151: Menu
  position:
    position-position-9411: Logo
    position-position-4664: 'Find Us'
    position-position-8841: 'Quick Links'
    position-position-7539: 'Send A message'
  branding:
    branding-5256: Branding
  mobile-menu:
    mobile-menu-9888: 'Mobile Menu'
inherit:
  default:
    header: header
    navigation: navigation
    abovefooter: abovefooter
    footer: footer
    offcanvas: offcanvas
    custom-2410: custom-5173
    social-6386: social-1900
    logo-6694: logo-7657
    menu-2151: menu-5263
    position-position-9411: position-position-5091
    position-position-4664: position-position-9943
    position-position-8841: position-position-5299
    position-position-7539: position-position-9218
    branding-5256: branding-4929
    custom-8180: custom-8697
    mobile-menu-9888: mobile-menu-7330
