version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1502553408
layout:
  header: {  }
  navigation: {  }
  /container-main/:
    -
      -
        'sidebar 20': {  }
      -
        'mainbar 60':
          -
            - system-messages-6091
          -
            - system-content-3910
          -
            - custom-5592
          -
            - custom-2850
      -
        'aside 20': {  }
  abovefooter: {  }
  footer: {  }
  offcanvas: {  }
structure:
  header:
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  sidebar:
    type: section
  mainbar:
    type: section
    attributes:
      class: ''
    block:
      variations: center
  container-main:
    attributes:
      boxed: ''
      class: 'section-horizontal-paddings section-vertical-paddings'
      extra: {  }
  abovefooter:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  custom-5592:
    title: 'Custom HTML'
    attributes:
      html: "The page you are looking for does not exist. We’re sorry but we can’t seem to find the page you requested.\n\n\n"
  custom-2850:
    title: 'Custom HTML'
    attributes:
      html: ' <a class="button er-bt" href="index.php"><i class="fa fa-arrow-circle-left"></i> Go to Home Page</a>'
