version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _offline
  timestamp: 1520018321
layout:
  header: {  }
  navigation: {  }
  /container-main/:
    -
      -
        'sidebar 20': {  }
      -
        'mainbar 60':
          -
            - system-content-1246
      -
        'aside 20': {  }
  abovefooter: {  }
  frame: {  }
  footer: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  sidebar:
    type: section
  mainbar:
    type: section
    attributes:
      class: ''
    block:
      variations: center
  container-main:
    attributes:
      boxed: ''
      class: 'section-horizontal-paddings section-vertical-paddings'
      extra: {  }
  abovefooter:
    type: section
  frame:
    type: section
  footer:
    inherit:
      outline: default
      include:
        - children
        - attributes
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
