name: _error
timestamp: 1530214457
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1520019792
positions: {  }
sections:
  header: Header
  navigation: Navigation
  sidebar: Sidebar
  mainbar: Mainbar
  abovefooter: Abovefooter
  frame: Frame
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-6091: 'System Messages'
  content:
    system-content-3910: 'Page Content'
  custom:
    custom-5592: 'Custom HTML'
    custom-2850: 'Custom HTML'
  logo:
    logo-4883: Logo
  menu:
    menu-4429: Menu
  branding:
    branding-1496: Branding
  mobile-menu:
    mobile-menu-9385: 'Mobile Menu'
inherit:
  default:
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    logo-4883: logo-7657
    menu-4429: menu-5263
    branding-1496: branding-4929
    mobile-menu-9385: mobile-menu-7330
